Creator "Messi on Thu Jun 6 13:20:52 2013"
graph
[
  node
  [
    id 1
  ]
  node
  [
    id 2
  ]
  node
  [
    id 3
  ]
  node
  [
    id 4
  ]
  node
  [
    id 5
  ]
  node
  [
    id 6
  ]
  node
  [
    id 7
  ]
  edge
  [
    source 1 
    target 2
  ]
  edge
  [
    source 1
    target 5
  ]
  edge
  [
    source 1
    target 6
  ]
  edge
  [
    source 2
    target 6
  ]
  edge
  [
    source 2
    target 3
  ]
  edge
  [
    source 3
    target 6
  ]
  edge
  [
    source 3
    target 7
  ]
  edge
  [
    source 4
    target 5
  ]
  edge
  [
    source 4
    target 6
  ]
  edge
  [
    source 4
    target 7
  ]
  edge
  [
    source 5
    target 6
  ]
  edge
  [
    source 6
    target 7
  ]
]
Creator "Generated by dsl_graph from test.csv"
graph
[
 directed 0 
 node
 [
  id 7
 ]
 node
 [
  id 6
 ]
 node
 [
  id 5
 ]
 node
 [
  id 4
 ]
 node
 [
  id 3
 ]
 node
 [
  id 2
 ]
 node
 [
  id 1
 ]
 edge
 [
  source 6
  target 7
  value 1

 ]
 edge
 [
  source 5
  target 6
  value 1

 ]
 edge
 [
  source 4
  target 7
  value 1

 ]
 edge
 [
  source 4
  target 6
  value 1

 ]
 edge
 [
  source 4
  target 5
  value 1

 ]
 edge
 [
  source 3
  target 7
  value 1

 ]
 edge
 [
  source 3
  target 6
  value 1

 ]
 edge
 [
  source 2
  target 6
  value 1

 ]
 edge
 [
  source 2
  target 3
  value 1

 ]
 edge
 [
  source 1
  target 6
  value 1

 ]
 edge
 [
  source 1
  target 5
  value 1

 ]
 edge
 [
  source 1
  target 2
  value 1

 ]
]Creator "Generated by dsl_graph from test.csv"
graph
[
 directed 0 
 node
 [
  id 7
 ]
 node
 [
  id 6
 ]
 node
 [
  id 5
 ]
 node
 [
  id 4
 ]
 node
 [
  id 3
 ]
 node
 [
  id 2
 ]
 node
 [
  id 1
 ]
 edge
 [
  source 6
  target 7
  value 1

 ]
 edge
 [
  source 5
  target 6
  value 1

 ]
 edge
 [
  source 4
  target 7
  value 1

 ]
 edge
 [
  source 4
  target 6
  value 1

 ]
 edge
 [
  source 4
  target 5
  value 1

 ]
 edge
 [
  source 3
  target 7
  value 1

 ]
 edge
 [
  source 3
  target 6
  value 1

 ]
 edge
 [
  source 2
  target 6
  value 1

 ]
 edge
 [
  source 2
  target 3
  value 1

 ]
 edge
 [
  source 1
  target 6
  value 1

 ]
 edge
 [
  source 1
  target 5
  value 1

 ]
 edge
 [
  source 1
  target 2
  value 1

 ]
]